### ISSUE TITLE
scikit_image-0.19 marching_cubes_lewiner deprecated

### ISSUE THREAD

**Issue by dslawinski-fp** [K3D-tools/chunky3d#20]
method no longer exists

`import chunky3d.vtk_utils as vtk_utils
/usr/local/lib/python3.7/site-packages/chunky3d/vtk_utils.py:514: in <module>
    from skimage.measure import marching_cubes_lewiner
E   ImportError: cannot import name 'marching_cubes_lewiner' from 'skimage.measure' (/usr/local/lib/python3.7/site-packages/skimage/measure/__init__.py)`

**Comment by tgandor** [comment]
Released: https://pypi.org/project/chunky3d/0.1.7/
